default_platform(:ios)

platform :ios do
  desc "Build and upload a new TestFlight build"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("APP_STORE_CONNECT_KEY_ID"),
      issuer_id: ENV.fetch("APP_STORE_CONNECT_ISSUER_ID"),
      key_content: ENV.fetch("APP_STORE_CONNECT_PRIVATE_KEY"),
      is_key_content_base64: true
    )

    update_code_signing_settings(
      use_automatic_signing: true,
      path: "livehive.xcodeproj",
      team_id: ENV.fetch("APPLE_TEAM_ID"),
      targets: ["myDeliveryApp"],
      code_sign_identity: "Apple Development"
    )

    update_code_signing_settings(
      use_automatic_signing: true,
      path: "livehive.xcodeproj",
      team_id: ENV.fetch("APPLE_TEAM_ID"),
      targets: ["widgetExtension"],
      code_sign_identity: "Apple Development"
    )

    increment_build_number(
      build_number: latest_testflight_build_number(
        api_key: api_key,
        initial_build_number: 1
      ) + 1
    )

    build_app(
      scheme: "myDeliveryApp",
      sdk: "iphoneos",
      destination: "generic/platform=iOS",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        signingStyle: "automatic",
        teamID: ENV.fetch("APPLE_TEAM_ID")
      },
      xcargs: [
        "-allowProvisioningUpdates",
        "-authenticationKeyPath #{ENV.fetch(\"APP_STORE_CONNECT_KEY_PATH\")}",
        "-authenticationKeyID #{ENV.fetch(\"APP_STORE_CONNECT_KEY_ID\")}",
        "-authenticationKeyIssuerID #{ENV.fetch(\"APP_STORE_CONNECT_ISSUER_ID\")}",
      ].join(" ")
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
