default_platform(:ios)

platform :ios do
  desc "Build and upload a new TestFlight build"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV.fetch("APP_STORE_CONNECT_KEY_ID"),
      issuer_id: ENV.fetch("APP_STORE_CONNECT_ISSUER_ID"),
      key_content: ENV.fetch("APP_STORE_CONNECT_PRIVATE_KEY"),
      is_key_content_base64: true
    )

    increment_build_number(
      build_number: latest_testflight_build_number(
        api_key: api_key,
        initial_build_number: 1
      ) + 1
    )

    build_app(
      scheme: "myDeliveryApp",
      sdk: "iphoneos",
      destination: "generic/platform=iOS",
      export_method: "app-store",
      export_options: {
        method: "app-store",
        signingStyle: "manual",
        teamID: ENV.fetch("APPLE_TEAM_ID"),
        provisioningProfiles: {
          "com.iandavis.livehive" => ENV.fetch("IOS_APP_PROFILE_SPECIFIER"),
          "com.iandavis.livehive.widget" => ENV.fetch("IOS_WIDGET_PROFILE_SPECIFIER")
        }
      },
      xcargs: [
        "CODE_SIGN_STYLE=Manual",
        "DEVELOPMENT_TEAM=#{ENV.fetch("APPLE_TEAM_ID")}",
        "OTHER_CODE_SIGN_FLAGS=--keychain #{ENV.fetch("BUILD_KEYCHAIN")}",
        "-authenticationKeyPath #{ENV.fetch("APP_STORE_CONNECT_KEY_PATH")}",
        "-authenticationKeyID #{ENV.fetch("APP_STORE_CONNECT_KEY_ID")}",
        "-authenticationKeyIssuerID #{ENV.fetch("APP_STORE_CONNECT_ISSUER_ID")}"
      ].join(" ")
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end
